name: workflowt1
on:
#   pull_request:
#        branches: [main]
    workflow_dispatch:
        inputs:
            entorno:
                required: true
                default: 'dev'
                type: choice 
                options:
                    - dev
                    - prod
                    - qa
jobs:
    primer_job:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
        environment: ${{ github.event.inputs.entorno || 'dev' }} 
        outputs:
            nombreVecino: "Jesus"
        steps: 
            - name: invocar-action-pr1
              id: action_t1
              uses: tareas-org/t1action@main
              with: 
                nombre: ${{ vars.NOMBRE }}
                apellido: ${{ vars.APELLIDO }}
                edad: ${{ vars.EDAD }}
            - name: Mostrar output de la action
              run: |
                    echo "La multiplcacion es: ${{ steps.action_t1.outputs.multiplicacion }}"

    llamado_reusablewf:
        uses: tareas-org/reusable-workflow/.github/workflows/rwf_t1.yml@main
        with: 
            nombre: 'Yex'
            
    jobOutputs:
        runs-on: ubuntu-latest
        needs: primer_job
        steps:
            - name: Mostrar output del job anterior
              run: |
                    echo "El nombre del vecino es: ${{ needs.primer_job.outputs.nombreVecino }}"
