name: workflowt1
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    primer_job:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name=='main'&&'prod'||github.ref_name=='develop'&&'dev'||github.ref_name=='release'&&'qa'}} 
        steps: 
            - name: action-PRT1
              uses: tareas-org/t1action@main
              with: 
                nombre: ${{ vars.NOMBRE }}
                apellido: ${{ vars.APELLIDO }}
                edad: ${{ vars.EDAD }}
