name: workflowt1
on:
    push:
        branches: [main, develop, release]
    workflow_dispatch:
jobs:
    primer_job:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name=='main'&&'prod'||github.ref_name=='develop'&&'dev'||github.ref_name=='release'&&'qa'}} 
        steps:
            - name: step-01
              run: |
                echo "Tarea 1 - CAMBIO DE EJEMPLO"
            